### ISSUE TITLE
Shortcuts are not supported on iPadOS or iOS 15 or older

### ISSUE THREAD

**Issue by kovimo** [ThatStella7922/battery-webhook#8]
Therefore it cannot be selected to create automation "Send Battery Info". I would like to use it on an iPad Air2 which cannot be updated beyond this OS version. I tried with an iPhone OS16.7.2 and a newer iPad with OS17.3. I could setup the automations following the documentation and both were sending notifications to Discord server. Is there any workaround?

**Comment by ThatStella7922** [comment]
Siri Shortcuts are currently not supported on iOS 15, they require iOS 16 or later [per the docs](<https://docs.thatstel.la/battery-webhook/docs/compatibility>). I hope to fix this in a future version of battery webhook, sorry for the inconvenience!

**Comment by kovimo** [comment]
Thanks for your feedback.
I was not aware that in this case Shortcuts is related to Siri. I thought
when charging condition is changed than an action is generated (Send
Battery Info) - without Siri.

So charging conditions of this old iPad cannot be transferred on an
automatic way with Battery Webhook app.
Please note that all other apps are listed on Shortcuts Actions page and
relevant actions can be selected.

Regards,
Imre

**Comment by ThatStella7922** [comment]
Shortcuts don’t require Siri but Apple calls them Siri Shortcuts for some reason.

Anyway, the reason that battery webhook needs iOS 16 or later for shortcuts is because I use the AppIntents framework which depends on iOS 16 or later.

**Comment by ThatStella7922** [comment]
This issue has been resolved with [version 1.3](https://github.com/ThatStella7922/battery-webhook/releases/tag/1.3) which has just been released

**Comment by ThatStella7922** [comment]
Closing as others have reported the issue being solved, please reopen if this is not the case.
